// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';

// LOGIN
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//PROFILE
export const PROFILE_DETAILS_START = 'PROFILE_DETAILS_START';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL';


export const USERS_START = 'USERS_START';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';

export const NOT_FOLLOWED_USERS_START = 'NOT_FOLLOWED_USERS_START';
export const NOT_FOLLOWED_USERS_SUCCESS = 'NOT_FOLLOWED_USERS_SUCCESS';
export const NOT_FOLLOWED_USERS_FAIL = 'NOT_FOLLOWED_USERS_FAIL';

export const TEST_FOLLOW_START = 'TEST_FOLLOW_START';
export const TEST_FOLLOW_SUCCESS = 'TEST_FOLLOW_SUCCESS';
export const TEST_FOLLOW_FAIL = 'TEST_FOLLOW_FAIL';

export const FOLLOW_START = 'FOLLOW_START';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAIL = 'FOLLOW_FAIL';

//POST

export const POSTS_START = 'POSTS_START';
export const POSTS_SUCCESS = 'POSTS_SUCCESS';
export const POSTS_FAIL = 'POSTS_FAIL';
export const POSTS_CLEAR = 'POSTS_CLEAR';
export const POSTS_CLEAR_SUCCESS = 'POSTS_CLEAR_SUCCESS';

export const USER_POSTS_START = 'USER_POSTS_START';
export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS';
export const USER_POSTS_FAIL = 'USER_POSTS_FAIL';

export const POST_COMMENTS_START = 'POST_COMMENTS_START';
export const POST_COMMENTS_SUCCESS = 'POST_COMMENTS_SUCCESS';
export const POST_COMMENTS_FAIL = 'POST_COMMENTS_FAIL';

export const ADD_POST_COMMENT_START = 'ADD_POST_COMMENT_START';
export const ADD_POST_COMMENT_SUCCESS = 'ADD_POST_COMMENT_SUCCESS';
export const ADD_POST_COMMENT_FAIL = 'ADD_POST_COMMENT_FAIL';

export const ADD_POST_REACT_START = 'ADD_POST_REACT_START';
export const ADD_POST_REACT_SUCCESS = 'ADD_POST_REACT_SUCCESS';
export const ADD_POST_REACT_FAIL = 'ADD_POST_REACT_FAIL';

export const NOT_LIKED_POSTS_START = 'NOT_LIKED_POSTS_START';
export const NOT_LIKED_POSTS_SUCCESS = 'NOT_LIKED_POSTS_SUCCESS';
export const NOT_LIKED_POSTS_FAIL = 'NOT_LIKED_POSTS_FAIL';

export const TEST_REACT_START = 'TEST_REACT_START';
export const TEST_REACT_SUCCESS = 'TEST_REACT_SUCCESS';
export const TEST_REACT_FAIL = 'TEST_REACT_FAIL';

export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const UPDATE_POST_START = 'UPDATE_POST_START';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';

export const CHANGE_POST_STATUS_START = 'CHANGE_POST_STATUS_START';
export const CHANGE_POST_STATUS_SUCCESS = 'CHANGE_POST_STATUS_SUCCESS';
export const CHANGE_POST_STATUS_FAIL = 'CHANGE_POST_STATUS_FAIL';

//CHAT

export const CHATS_START = 'CHATS_START';
export const CHATS_SUCCESS = 'CHATS_SUCCESS';
export const CHATS_FAIL = 'CHATS_FAIL';
export const CHATS_CLEAR = 'CHATS_CLEAR';
export const CHATS_CLEAR_SUCCESS = 'CHATS_CLEAR_SUCCESS';

export const MESSAGES_START = 'MESSAGES_START';
export const MESSAGES_SUCCESS = 'MESSAGES_SUCCESS';
export const MESSAGES_FAIL = 'MESSAGES_FAIL';
export const MESSAGES_CLEAR = 'MESSAGES_CLEAR';
export const MESSAGES_CLEAR_SUCCESS = 'MESSAGES_CLEAR_SUCCESS';

//DISCUSSION

export const CREATE_DISCUSSION_START = 'CREATE_DISCUSSION_START';
export const CREATE_DISCUSSION_SUCCESS = 'CREATE_DISCUSSION_SUCCESS';
export const CREATE_DISCUSSION_FAIL = 'CREATE_DISCUSSION_FAIL';

export const UPDATE_DISCUSSION_START = 'UPDATE_DISCUSSION_START';
export const UPDATE_DISCUSSION_SUCCESS = 'UPDATE_DISCUSSION_SUCCESS';
export const UPDATE_DISCUSSION_FAIL = 'UPDATE_DISCUSSION_FAIL';

export const CHANGE_DISCUSSION_STATUS_START = 'CHANGE_DISCUSSION_STATUS_START';
export const CHANGE_DISCUSSION_STATUS_SUCCESS = 'CHANGE_DISCUSSION_STATUS_SUCCESS';
export const CHANGE_DISCUSSION_STATUS_FAIL = 'CHANGE_DISCUSSION_STATUS_FAIL';

export const DISCUSSIONS_START = 'DISCUSSIONS_START';
export const DISCUSSIONS_SUCCESS = 'DISCUSSIONS_SUCCESS';
export const DISCUSSIONS_FAIL = 'DISCUSSIONS_FAIL';

export const USER_DISCUSSIONS_START = 'USER_DISCUSSIONS_START';
export const USER_DISCUSSIONS_SUCCESS = 'USER_DISCUSSIONS_SUCCESS';
export const USER_DISCUSSIONS_FAIL = 'USER_DISCUSSIONS_FAIL';

export const DISCUSSION_COMMENTS_START = 'DISCUSSION_COMMENTS_START';
export const DISCUSSION_COMMENTS_SUCCESS = 'DISCUSSION_COMMENTS_SUCCESS';
export const DISCUSSION_COMMENTS_FAIL = 'DISCUSSION_COMMENTS_FAIL';

export const ADD_DISCUSSION_COMMENT_START = 'ADD_DISCUSSION_COMMENT_START';
export const ADD_DISCUSSION_COMMENT_SUCCESS = 'ADD_DISCUSSION_COMMENT_SUCCESS';
export const ADD_DISCUSSION_COMMENT_FAIL = 'ADD_DISCUSSION_COMMENT_FAIL';

export const ADD_DISCUSSION_REACT_START = 'ADD_DISCUSSION_REACT_START';
export const ADD_DISCUSSION_REACT_SUCCESS = 'ADD_DISCUSSION_REACT_SUCCESS';
export const ADD_DISCUSSION_REACT_FAIL = 'ADD_DISCUSSION_REACT_FAIL';

//NOTIFICATION

export const NOTIFICATIONS_START = 'NOTIFICATIONS_START';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAIL = 'NOTIFICATIONS_FAIL';

export const DELETE_NOTIFICATIONS_START = 'DELETE_NOTIFICATIONS_START';
export const DELETE_NOTIFICATIONS_SUCCESS = 'DELETE_NOTIFICATIONS_SUCCESS';
export const DELETE_NOTIFICATIONS_FAIL = 'DELETE_NOTIFICATIONS_FAIL';

export const READ_NOTIFICATIONS_START = 'READ_NOTIFICATIONS_START';
export const READ_NOTIFICATIONS_SUCCESS = 'READ_NOTIFICATIONS_SUCCESS';
export const READ_NOTIFICATIONS_FAIL = 'READ_NOTIFICATIONS_FAIL';


